a=input('Digite algo: ')
print('O tipo primitivo desse valor e',type(a))
print('Só tem espaços?',a.isspace())
print('Só tem números?',a.isnumeric())
print('é alfabético?',a.isalpha())
print('é alphanumerico?',a.isalnum())
print('é maiusculo?',a.isupper())
print('é minusculo?',a.islower())
print('está capitalizada?',a.istitle())